### ISSUE TITLE
Variable Book Cover

### ISSUE THREAD

**Issue by eeriemyxi** [Librum-Reader/Librum#134]
**Feature Description**
A few books from my collection don't print the book cover on the initial page, but it is accessible on another page. Librum picks the initial page of the book as its cover, and the only alternative provided is to load an image externally, which is uneasily more dependent on my filesystem than I fancy.

**Implementation Details**
In the "Book details" section of a book, there could be a text field "Book cover page", defaulting to `1`, that is checked on startup. Alternatively, the "Change" button could offer a menu asking whether to set a book page or load an image. 

**Additional Context**
![image](https://github.com/Librum-Reader/Librum/assets/86738916/2bab3e4c-2c33-48cf-829e-faadd4899ba2)

**Comment by DavidLazarescu** [comment]
Thanks for the proposal. This would be doable but quite complicated, requiring re-initialization of the book due to the way we currently extract meta-data. We have looked into a way to find the cover page automatically, but the underlying library we use for extracting pages from books sadly doesn't provide this functionality.

Changing the book cover (selecting a local file) does not depend on your file-system at all though. When you change the book cover, the new one is uploaded to the server as book metadata and kept locally on your device in a storage location librum uses for your book metadata. Thus you can delete the image after you have changed it in the application.

**Comment by eeriemyxi** [comment]
> Changing the book cover (selecting a local file) does not depend on your file-system at all though. When you change the book cover, the new one is uploaded to the server as book metadata and kept locally on your device in a storage location librum uses for your book metadata. Thus you can delete the image after you have changed it in the application.

Thank you for the clarification. This is good enough, I think.
