### ISSUE TITLE
RSVP mode

### ISSUE THREAD

**Issue by Vilhelm-Ian** [Librum-Reader/Librum#2]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I have to move my eyes to read

**Describe the solution you'd like**
A button to press and the text starts to flip through the screen

**Describe alternatives you've considered**

**Additional context**
https://play.google.com/store/apps/details?id=azagroup.reedy&gl=US here is an application that perfectly integrates RSVP

**Comment by Creapermann** [comment]
@Vilhelm-Ian, what does RSVP stand for? please elaborate.
If you mean automatic scrolling, this is a feature which is planned to be implemented

**Comment by Vilhelm-Ian** [comment]
stands for [Rapid serial visual presentation](https://en.wikipedia.org/wiki/Rapid_serial_visual_presentation)

here is a demenonstration ![alt text](https://habrastorage.org/getpro/habr/post_images/600/c2a/49d/600c2a49d6088cf2f9eb73552877abed.gif)

**Comment by Creapermann** [comment]
This seems like a very specific feature to me. I dont think I'll have time to add this any soon, but maybe after some of the other major features are implemented, I'll take a look at this again. Since Librum is opensource and everyone is allowed to edit and redistrubute it, there might be someone else who can contribute it to Librum
