### ISSUE TITLE
Migrate to conan

### ISSUE THREAD

**Issue by nrbnlulu** [Librum-Reader/Librum#26]
Cloning the repo with `--recursive` flag takes decades. I would suggest to use conan for dependencies.

**Comment by DavidLazarescu** [comment]
Thanks for the feedback. 
I know that cloning takes quite a bit due to the dependency on mupdf (https://github.com/ArtifexSoftware/mupdf). I think adding `-j 8` or similar to it might help.
We will look into conan for our dependencies, but we have different priorities for now, so we may not have the time to look into that right now.
