### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by rodrigogonegit** [Librum-Reader/Librum#64]
**Is your feature request related to a problem? Please describe.**
I'd like to have an android app or a responsive web app.

**Describe the solution you'd like**
I'd like to have an android app or a responsive web app.

**Describe alternatives you've considered**
An alternative would be to read on my laptop, which is not ideal for me.

**Additional context**
I have close to zero android dev experience, but I'm up to contribute.

**Comment by DavidLazarescu** [comment]
An android app is planned, and we will start working on it pretty soon.
It will take some time until we have it done though, since we need to plan and implement a new UI and adapt the application to run on android.

Any contributions, no matter if code-wise, financial or design wise are very welcomed and will help us speed up the problem. ä

**Comment by rodrigogonegit** [comment]
Thanks for the quick reply. Is there a discussion thread about it? Or some initial doc

**Comment by DavidLazarescu** [comment]
> Thanks for the quick reply. Is there a discussion thread about it? Or some initial doc 

Not yet, I will open a discussion once we start working on it.

**Comment by rodrigogonegit** [comment]
Any news on this?

**Comment by DavidLazarescu** [comment]
Yes, check the platform/android branch to see the latest changes. We are working on it.

**Comment by zeroishero** [comment]
There seems to be an app named Librum already in Play store. It's a bible reading app.
